unless ENV['TRAVIS']
  require 'simplecov'
  SimpleCov.start
end

require 'bundler/setup'

require 'us_bank_holidays'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.fail_fast = true
end
